/* Generated by 'Generate-Swift-L18N-Constants.swift' DO NOT CHANGE */

import Foundation

/**
Usage:

Localized.LoadError
Localized.WelcomeMessage.with("Dan")
*/

enum Localized: CustomStringConvertible
{
	class Bundles {
    static let framework = Bundle(for: Localized.Bundles.self)
  }

	// %CASE_DECLARATIONS%
	var key : String
	{
		switch self
		{
			// %CASE_DESCRIPTIONS%
		}
	}
	
	var description : String
	{
		return NSLocalizedString(self.key, tableName: nil, bundle: Localized.Bundles.framework, value: self.key, comment: self.key)
	}
	
	func with(args: CVarArg...) -> String
	{
		let format = description
		return String(format: format, arguments: args)
	}
}
