/* Generated by 'Generate-Swift-L18N-Constants.swift' DO NOT CHANGE */

import Foundation

/**
Usage:

Localized.LoadError
Localized.WelcomeMessage.with("Dan")
*/

enum Localized: CustomStringConvertible
{
	case AppTesting
	case AppWelcomeMessage

	var key : String
	{
		switch self
		{
			case .AppTesting:
					return "app.testing"
			case .AppWelcomeMessage:
					return "app.welcome.message"
		}
	}
	
	var description : String
	{
		return NSLocalizedString(self.key, comment: self.key)
	}
	
	func with(args: CVarArgType...) -> String
	{
		let format = NSLocalizedString(self.key, comment: self.key)
		return String(format: format, arguments: args)
	}
}
