/* Generated by 'Generate-Swift-L18N-Constants.swift' DO NOT CHANGE */

import Foundation

/**
Usage:

Localized.LoadError.string()
Localized.WelcomeMessage.string("Dan")
*/

enum Localized: CustomStringConvertible
{
	
	case MyString

	
	var description : String
		{
			switch self
			{
				
				case .MyString:
					return "my.string"

			}
	}
	
	func string(args: CVarArgType...) -> String
	{
		let format = NSLocalizedString(self.description, comment: self.description)
		return String(format: format, arguments: args)
	}
}