/* Generated by 'Generate-Swift-L18N-Constants.swift' DO NOT CHANGE */

import Foundation

/**
Usage:

Localized.LoadError.string()
Localized.WelcomeMessage.string("Dan")
*/

enum Localized: CustomStringConvertible
{
	// %CASE_DECLARATIONS%
	var description : String
	{
		switch self
		{
			// %CASE_DESCRIPTIONS%
		}
	}
	
	func string(args: CVarArgType...) -> String
	{
		let format = NSLocalizedString(self.description, comment: self.description)
		return String(format: format, arguments: args)
	}
	
}