/* Generated by 'Generate-Swift-L18N-Constants.swift' DO NOT CHANGE */

import Foundation

/**
Usage:

Localized.LoadError.string()
Localized.WelcomeMessage.string("Dan")
*/

enum Localized: CustomStringConvertible
{
	
	// %CASE_DECLARATIONS%
	
//	case Burberry
//	case LoadError
//	case PageCount
//	case CountdownNumber
//	case CountdownUnitDays
//	case CountdownUnitHours
//	case CountdownUnitMinutes
//	case CountdownUnitSeconds
	
	var description : String
		{
			switch self
			{
				
				// %CASE_DESCRIPTIONS%
//				
//			case .Burberry:
//				return "app.burberry"
//			case .LoadError:
//				return "app.error.load"
//				
//			case .PageCount:
//				return "menu.pagecount.of"
//				
//			case .CountdownNumber:
//				return "countdown.unit.number"
//			case .CountdownUnitDays:
//				return "countdown.unit.days"
//			case .CountdownUnitHours:
//				return "countdown.unit.hours"
//			case .CountdownUnitMinutes:
//				return "countdown.unit.minutes"
//			case .CountdownUnitSeconds:
//				return "countdown.unit.seconds"
			}
	}
	
	func string(args: CVarArgType...) -> String
	{
		let format = NSLocalizedString(self.description, comment: self.description)
		return String(format: format, arguments: args)
	}
}